# Generated by Django 4.2.21 on 2025-07-21 11:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Code ISO')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la devise')),
            ],
            options={
                'verbose_name': 'Devise Officielle',
                'verbose_name_plural': 'Devises Officielles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ZoneMonetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la zone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Statut Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zone Monétaire',
                'verbose_name_plural': 'Zones Monétaires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DeviseAlias',
            fields=[
                ('alias', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Nom brut / Alias')),
                ('devise_officielle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.devise')),
            ],
            options={
                'verbose_name': 'Alias de Devise',
                'verbose_name_plural': 'Alias de Devises',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='source', serialize=False, to='core.zonemonetaire')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la source')),
                ('url_source', models.URLField(max_length=255, verbose_name='URL de la source de données')),
                ('scraper_filename', models.CharField(max_length=100, verbose_name='Nom du fichier scraper')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('delai_execution', models.IntegerField(default=0, verbose_name="Délai d'exécution du scraper (secondes)")),
                ('periodic_task', models.OneToOneField(blank=True, help_text='La tâche planifiée Celery Beat pour ce scraper.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'Source de Données',
                'verbose_name_plural': 'Sources de Données',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_publication', models.DateField(db_index=True)),
                ('taux_source', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Taux brut de la source')),
                ('multiplicateur_source', models.IntegerField(default=1, verbose_name='Multiplicateur de la source')),
                ('taux_normalise', models.DecimalField(decimal_places=9, max_digits=18, verbose_name='Taux normalisé (par unité)')),
                ('date_creation_interne', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(db_index=True, default=False, verbose_name='Est le taux le plus récent')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='core.devise')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='core.zonemonetaire')),
            ],
            options={
                'verbose_name': 'Taux de Change Final',
                'verbose_name_plural': 'Taux de Change Finals',
                'ordering': ['-date_publication', 'devise'],
                'unique_together': {('devise', 'zone', 'date_publication')},
            },
        ),
        migrations.CreateModel(
            name='ActivatedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name="Statut d'activation")),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='core.devise')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activated_currencies', to='core.zonemonetaire')),
            ],
            options={
                'verbose_name': 'Devise Activée par Zone',
                'verbose_name_plural': 'Devises Activées par Zone',
                'unique_together': {('zone', 'devise')},
            },
        ),
        migrations.CreateModel(
            name='ScrapedCurrencyRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_publication_brut', models.DateField(blank=True, null=True, verbose_name='Date de publication brute')),
                ('nom_devise_brut', models.CharField(blank=True, max_length=100, verbose_name='Nom de la devise brute')),
                ('code_iso_brut', models.CharField(blank=True, max_length=10, verbose_name='Code ISO brut')),
                ('valeur_brute', models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=18, verbose_name='Valeur brute du taux')),
                ('multiplicateur_brut', models.IntegerField(default=1)),
                ('date_scraping', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='core.source')),
            ],
            options={
                'verbose_name': 'Donnée Brute Scrapée',
                'verbose_name_plural': 'Données Brutes Scrapées',
                'ordering': ['-date_publication_brut', '-date_scraping'],
                'unique_together': {('source', 'date_publication_brut', 'nom_devise_brut', 'code_iso_brut')},
            },
        ),
    ]
