# Generated by Django 5.2.3 on 2025-06-20 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonemonetaire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zonemonetaire',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
