# Generated by Django 4.2.21 on 2025-08-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedcurrencyraw',
            name='code_iso_brut',
            field=models.CharField(blank=True, max_length=100, verbose_name='Code ISO brut'),
        ),
    ]
