# Generated by Django 5.2.3 on 2025-06-20 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_zonemonetaire_date_creation_alter_zonemonetaire_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceTaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('url_source', models.URLField()),
                ('scraper_filename', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.zonemonetaire')),
            ],
        ),
    ]
