# Generated by Django 5.2.3 on 2025-06-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sourcetaux'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonemonetaire',
            options={'ordering': ['nom'], 'verbose_name': 'Zone Monétaire', 'verbose_name_plural': 'Zones Monétaires'},
        ),
        migrations.AddField(
            model_name='zonemonetaire',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Statut Actif'),
        ),
        migrations.AlterField(
            model_name='zonemonetaire',
            name='nom',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom de la zone'),
        ),
    ]
