# Generated by Django 5.2.3 on 2025-06-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_zonemonetaire_options_zonemonetaire_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Code ISO')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la devise')),
            ],
            options={
                'verbose_name': 'Devise Officielle',
                'verbose_name_plural': 'Devises Officielles',
                'ordering': ['code'],
            },
        ),
    ]
