# Generated by Django 5.2.3 on 2025-06-25 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_devise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='source', serialize=False, to='core.zonemonetaire')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la source')),
                ('url_source', models.URLField(max_length=255, verbose_name='URL de la source de données')),
                ('scraper_filename', models.CharField(max_length=100, verbose_name='Nom du fichier scraper')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Source de Données',
                'verbose_name_plural': 'Sources de Données',
            },
        ),
        migrations.CreateModel(
            name='ActivatedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name="Statut d'activation")),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='core.devise')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activated_currencies', to='core.zonemonetaire')),
            ],
            options={
                'verbose_name': 'Devise Activée par Zone',
                'verbose_name_plural': 'Devises Activées par Zone',
                'unique_together': {('zone', 'devise')},
            },
        ),
        migrations.CreateModel(
            name='CurrencyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_devise_brut', models.CharField(max_length=100, unique=True, verbose_name='Nom de la devise brute scrapée')),
                ('multiplicateur_a_appliquer', models.IntegerField(default=1)),
                ('devise_officielle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.devise')),
            ],
            options={
                'verbose_name': 'Mapping de Devise',
                'verbose_name_plural': 'Mappings de Devises',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_publication', models.DateField(db_index=True)),
                ('valeur_achat', models.DecimalField(decimal_places=6, max_digits=18)),
                ('valeur_vente', models.DecimalField(decimal_places=6, max_digits=18)),
                ('date_creation_interne', models.DateTimeField(auto_now_add=True)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='core.devise')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='core.zonemonetaire')),
            ],
            options={
                'verbose_name': 'Taux de Change Final',
                'verbose_name_plural': 'Taux de Change Finals',
                'ordering': ['-date_publication', 'devise'],
                'unique_together': {('devise', 'zone', 'date_publication')},
            },
        ),
        migrations.CreateModel(
            name='ScrapedCurrencyRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_devise_brut', models.CharField(max_length=100, verbose_name='Nom de la devise brute')),
                ('valeur_achat_brut', models.CharField(max_length=50, verbose_name="Valeur d'achat brute")),
                ('valeur_vente_brut', models.CharField(max_length=50, verbose_name='Valeur de vente brute')),
                ('multiplicateur_brut', models.IntegerField(default=1)),
                ('date_scraping', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='core.source')),
            ],
            options={
                'verbose_name': 'Donnée Brute Scrapée',
                'verbose_name_plural': 'Données Brutes Scrapées',
                'ordering': ['-date_scraping'],
            },
        ),
        migrations.DeleteModel(
            name='SourceTaux',
        ),
    ]
