# Generated by Django 5.2.3 on 2025-06-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_source_activatedcurrency_currencymapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedcurrencyraw',
            name='date_publication_brut',
            field=models.CharField(default='non spécifiée', max_length=20, verbose_name='Date de publication brute'),
        ),
    ]
