# Generated by Django 5.2.3 on 2025-06-27 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_populate_devises'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviseAlias',
            fields=[
                ('alias', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Nom brut / Alias')),
                ('devise_officielle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.devise')),
            ],
            options={
                'verbose_name': 'Alias de Devise',
                'verbose_name_plural': 'Alias de Devises',
            },
        ),
        migrations.DeleteModel(
            name='CurrencyMapping',
        ),
    ]
