# Generated by Django 5.2.3 on 2025-07-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_devisealias_delete_currencymapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedcurrencyraw',
            name='code_iso_brut',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code ISO brut'),
        ),
        migrations.AlterField(
            model_name='scrapedcurrencyraw',
            name='nom_devise_brut',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom de la devise brute'),
        ),
        migrations.AlterField(
            model_name='scrapedcurrencyraw',
            name='valeur_achat_brut',
            field=models.CharField(blank=True, max_length=50, verbose_name="Valeur d'achat brute"),
        ),
        migrations.AlterField(
            model_name='scrapedcurrencyraw',
            name='valeur_vente_brut',
            field=models.CharField(blank=True, max_length=50, verbose_name='Valeur de vente brute'),
        ),
    ]
