# Generated by Django 5.2.3 on 2025-07-01 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_scrapedcurrencyraw_code_iso_brut_and_more'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='periodic_task',
            field=models.OneToOneField(blank=True, help_text='La tâche planifiée Celery Beat pour ce scraper.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask'),
        ),
    ]
