# Generated by Django 5.2.3 on 2025-07-02 10:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_source_periodic_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapedcurrencyraw',
            options={'ordering': ['-date_publication_brut', '-date_scraping'], 'verbose_name': 'Donnée Brute Scrapée', 'verbose_name_plural': 'Données Brutes Scrapées'},
        ),
        migrations.RenameField(
            model_name='exchangerate',
            old_name='valeur_achat',
            new_name='taux',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='valeur_vente',
        ),
        migrations.AlterUniqueTogether(
            name='scrapedcurrencyraw',
            unique_together={('source', 'date_publication_brut', 'nom_devise_brut', 'code_iso_brut')},
        ),
        migrations.AddField(
            model_name='scrapedcurrencyraw',
            name='valeur_brute',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=18, verbose_name='Valeur brute du taux'),
        ),
        migrations.AlterField(
            model_name='scrapedcurrencyraw',
            name='date_publication_brut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de publication brute'),
        ),
        migrations.RemoveField(
            model_name='scrapedcurrencyraw',
            name='valeur_achat_brut',
        ),
        migrations.RemoveField(
            model_name='scrapedcurrencyraw',
            name='valeur_vente_brut',
        ),
    ]
