# Generated by Django 5.2.3 on 2025-07-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_scrapedcurrencyraw_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='taux',
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='is_latest',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est le taux le plus récent'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='multiplicateur_source',
            field=models.IntegerField(default=1, verbose_name='Multiplicateur de la source'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='taux_normalise',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=18, verbose_name='Taux normalisé (par unité)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='taux_source',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Taux brut de la source'),
            preserve_default=False,
        ),
    ]
