# Generated by Django 4.2.21 on 2025-07-30 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uinotification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'UI Notification', 'verbose_name_plural': 'UI Notifications'},
        ),
        migrations.AddField(
            model_name='logentry',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_related_logs', to='core.source'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_related_logs', to='core.zonemonetaire'),
        ),
        migrations.AlterField(
            model_name='uinotification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ui_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
