# Generated by Django 4.2.21 on 2025-07-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_uinotification_options_logentry_source_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UINotification',
        ),
    ]
