# Generated by Django 4.2.21 on 2025-08-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_delete_uinotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
